forms/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'forms'
urlpatterns = [
    path('', views.index, name='index'),
    path('mi_prestamo', views.mi_prestamo, name='mi_prestamo'),
    path('prestamos_admin', views.admin, name='admin'),
    path('registrar_admin', views.registrar_admin, name='registrar_admin'),
    path('salir_admin', views.salir_admin, name='salir_admin'),


    path('cambiar_estado/<int:id>', views.cambiar_estado, name='cambiar_estado'),
    path('borrar/<int:id>', views.borrar, name='borrar'),

]

prestamisto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('forms.urls')),
    #path('admin/', admin.site.urls),
]

forms/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.core.validators import validate_email, RegexValidator
from email_validator import validate_email, EmailNotValidError
from forms.constants import GENERO


alnumValidator = RegexValidator(r'^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')



class Prestamos(models.Model):
    dni = models.IntegerField()
    nombre = models.CharField(max_length=20, validators=[alnumValidator])
    apellido = models.CharField(max_length=20, validators=[alnumValidator])
    genero = models.CharField(max_length=1, choices=GENERO)
    email = models.EmailField(max_length=254, validators=[validate_email])
    monto = models.IntegerField()
    estado = models.BooleanField(default=False)

    def __str__(self):
        return self.nombre

forms/admin.py
from django.contrib import admin

# Register your models here.

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

forms/constants.py
GENERO =[("F", "FEMENINO"), ("M", "MASCULINO")]

forms/forms.py
from django import forms

from forms.constants import GENERO
from forms.models import Prestamos


class RegistrarPrestamo(forms.ModelForm):
    class Meta:
        model = Prestamos
        fields = [
            "dni",
            "nombre",
            "apellido",
            "genero",
            "email",
            "monto",
        ]
        labels = {
            "dni": "DNI",
            "nombre": "Nombre",
            "apellido": "Apellido",
            "genero": "Genero",
            "email": "E-mail",
            "monto": "Monto",
        }
        widgets = {
            "dni": forms.NumberInput(attrs={'min': 20000000, 'max': 99999999, 'class': "form-control"}),
            "nombre": forms.TextInput(attrs={'class': "form-control"}),
            "apellido": forms.TextInput(attrs={'class': "form-control"}),
            "genero": forms.Select(attrs={'class': "form-control"}),
            "email": forms.EmailInput(attrs={'class': "form-control"}),
            "monto": forms.NumberInput(attrs={'min': 1, 'max': 100000000000, 'class': "form-control"}),

        }

forms/services.py
import requests



def pre_score(dni):
    #URL = "http://nicanor.lan/test.html"
    URL = "https://api.moni.com.ar/api/v4/scoring/pre-score"
    headers = {'credential': 'ZGpzOTAzaWZuc2Zpb25kZnNubm5u'}
    response = requests.get(URL + "/" + dni, headers=headers)
    if response.status_code == 200:
        response_json = response.json()
        #print("api rta: %s" % response_json)
        has_error = bool(response_json.get("has_error"))
        status = str(response_json.get("status"))

    return status == "approve" and not has_error
    #return True

forms/tests.py
from django.test import TestCase

# Create your tests here.

forms/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login as do_login
from django.contrib.auth import logout as do_logout

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from email_validator import validate_email

from . import services
from .forms import RegistrarPrestamo
from .models import Prestamos



def index(request):
    return render(request,'index.html')


def mi_prestamo(request):
    if request.method == "POST":
        form = RegistrarPrestamo(request.POST)
        email = request.POST.get("email", "")
        if ( form.is_valid()):
            dni = request.POST.get("dni", "")
            nombre = request.POST.get("nombre", "")
            apellido = request.POST.get("apellido", "")
            genero = request.POST.get("genero", "")
            monto = request.POST.get("monto", "")
            try:
                solicitud = Prestamos.objects.get(dni=int(dni))
            except:
                solicitud = form
                solicitud.estado = services.pre_score(dni)
                solicitud.monto = monto
                solicitud.save()
            contexto = {
                "dni": dni,
                "nombre": nombre,
                "apellido": apellido,
                "genero": genero,
                "email": email,
                "monto": solicitud.monto,
                "resultado": solicitud.estado
            }
            solicitud.save()
            return render(request, "forms/mi_prestamo_resultado.html", {"contexto": contexto})
        else:
            return render(request, 'forms/mi_prestamo.html', {'register_form': form, "errores": ["email icorrecto"]})
    register_form = RegistrarPrestamo()
    return render(request, 'forms/mi_prestamo.html', {'register_form': register_form, "errores": []})


def admin(request):
    contexto = {}
    if request.user.is_authenticated:
        contexto["is_authenticated"] = request.user.is_authenticated
        contexto["prestamos"] = Prestamos.objects.all()
        return render(request, 'admin/prestamos_panel.html', {'contexto': contexto})
    else:
        form = AuthenticationForm()
        if request.method == "POST":
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = authenticate(username=username, password=password)
                if user is not None:
                    do_login(request, user)
                    return redirect('/prestamos_admin')

        return render(request, "admin/prestamos_panel.html", {'login_form': form})

def salir_admin(request):
    do_logout(request)
    return redirect('/')

def registrar_admin(request):
    form = UserCreationForm()
    form.fields['username'].help_text = None
    form.fields['password1'].help_text = None
    form.fields['password2'].help_text = None
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            if user is not None:
                do_login(request, user)
                return redirect('/prestamos_admin')

    return render(request, "admin/registrar.html", {'form': form})


def cambiar_estado(request,id):
    try:
        if(id>0):
            prestamo = Prestamos.objects.get(id=int(id))
            prestamo.estado = not prestamo.estado
            prestamo.save()
    except:
        pass
    return HttpResponseRedirect("/prestamos_admin")


def borrar(request,id):
    try:
        if(id>0):
            prestamo = Prestamos.objects.get(id=int(id))
            prestamo.delete()
    except:
        pass
    return HttpResponseRedirect("/prestamos_admin")

forms/templates/base.html
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

forms/templates/forms/mi_prestamo.html
<!DOCTYPE html>
<html lang="es"><head>
  {% include "../base.html" %}
  <div>
        <a href="/">Inicio</a>
  </div>
  <title>Mis forms</title>


</head><body>
  <div class="container text-center pt-5">
    <h1>Hola</h1>
    <p>Solicitar prestamo</p>
    {% if errores%}
    {% for e in errores %}
        <p class="text-danger" >{{ e }}</p>
    {% endfor %}
    {% endif %}
    <div class='jumbotron'>
      <center>
        <div class="text-left" style="max-width:500px">
          <form action="{% url 'forms:mi_prestamo' %}" method="post">
            {% csrf_token %}
            {% for field in register_form %}
            <div class='form-group'>
              <label for="{{ field.name }}">{{ field.label }}</label>
              {{ field }}
            </div>
            {% endfor %}
            <br>
            <center><button type="submit" class="btn btn-success btn-lg">Registrar prestamo</button></center>
          </form>
        </div>

      </center>
    </div>
  </div>

</body>
</html>

forms/templates/forms/mi_prestamo_resultado.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% include "../base.html" %}
    <div>
        <a href="/">Inicio</a>
    </div>
    <title>Mis Prestamos</title>

</head>
<body>
 <div class="container text-center pt-5">
        <h1>Hola {{ contexto.nombre }}!!</h1>
        <div class='jumbotron'>
            <center>
                <pre>
                <p>Tu prestamo de: ${{ contexto.monto }}  se encuentra {% if contexto.resultado %} aprobado! {% else %} desaprobado :({% endif %} </p>
            </pre>

            </center>
        </div>
    </div>


</body>
</html>

forms/templates/index.html
<!DOCTYPE html>
<html lang="es">
    <title>Inicio</title>
<head>
    {% include "base.html" %}
</head>
<body>
    <div class="container text-center pt-5">
        <h1>Hola</h1>
        <div class='jumbotron'>
            <center>
                <p><a href="/mi_prestamo">Solicitar Prestamo</a></p>
                <p><a href="/prestamos_admin">Acceso Admin</a></p>
            </center>
        </div>
    </div>
</body>
</html>